te_la_arriendo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from main.views import home, inmueble_detail, solo_arrendadores, solo_arrendatarios, profile, edit_user, change_password, register
from inmuebles.views import nuevo_inmueble, crear_inmueble, editar_inmueble, eliminar_inmueble

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', home, name='home'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/change-pass/', change_password, name='change_password'),
    path('edit-user/', edit_user, name='edit_user'),
    path('accounts/register/', register, name='register'),
    # Estas son parte de la clase de hoy, no del proyecto
    path('arrendadores/', solo_arrendadores, name='solo_arrendadores'),
    path('arrendatarios/', solo_arrendatarios, name='solo_arrendatarios'),
    path('inmuebles/nuevo/', nuevo_inmueble, name='nuevo_inmueble'),
    path('inmuebles/crear/', crear_inmueble, name='crear_inmueble'),
    path('inmuebles/editar/<id>/', editar_inmueble, name='editar_inmueble'),
    path('inmuebles/eliminar/<id>/', eliminar_inmueble, name='eliminar_inmueble'),
    path('inmueble/<int:pk>/', inmueble_detail, name='inmueble_detail_modal'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inmuebles/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
# Create your models here.


class UserProfile(models.Model):
  # User: username(rut), email, first_name, last_name, password
  roles = (('arrendador', 'Arrendador'), ('arrendatario', 'Arrendatario'), ('admin', 'Admin'))
  user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
  direccion = models.CharField(max_length=255)
  telefono = models.CharField(max_length=255, null=True, blank=True)
  rol = models.CharField(max_length=255, choices=roles, default='arrendatario')

  def __str__(self):
    return f'{self.user.first_name} {self.user.last_name} ({self.rol})'

class Region(models.Model):
  cod = models.CharField(max_length=2, primary_key=True)
  nombre = models.CharField(max_length=255)

  def __str__(self) -> str:
    return f'{self.nombre} ({self.cod})'

class Comuna(models.Model):
  cod = models.CharField(max_length=5, primary_key=True)
  nombre = models.CharField(max_length=255)
  region = models.ForeignKey(Region, on_delete=models.RESTRICT, related_name='comunas')

  def __str__(self) -> str:
    return f'{self.nombre} ({self.cod})'


class Inmueble(models.Model):
  tipos = (('casa', 'Casa'), ('departamento', 'Departamento'), ('bodega', 'Bodega'), ('parcela', 'Parcela'))

  nombre = models.CharField(max_length=50)
  descripcion = models.TextField(max_length=1500)
  m2_construidos = models.IntegerField(validators=[MinValueValidator(1)])
  m2_totales = models.IntegerField(validators=[MinValueValidator(1)])
  num_estacionamientos = models.IntegerField(validators=[MinValueValidator(0)], default=0)
  num_habitaciones = models.IntegerField(validators=[MinValueValidator(1)], default=1)
  num_baños = models.IntegerField(validators=[MinValueValidator(0)], default=0)
  direccion = models.CharField(max_length=255)
  tipo_inmueble = models.CharField(max_length=255, choices=tipos)
  precio = models.IntegerField(validators=[MinValueValidator(1000)], null=True)
  precio_ufs = models.FloatField(validators=[MinValueValidator(1.0)], null=True)
  imagen = models.ImageField(upload_to='inmuebles/', null=True, blank=True)  # Agregar campo de imagen
  # llaves foráneas
  comuna = models.ForeignKey(Comuna, related_name='inmuebles', on_delete=models.RESTRICT)
  propietario = models.ForeignKey(User, on_delete=models.RESTRICT, related_name='inmuebles')

  def __str__(self):
        return self.nombre


class Solicitud(models.Model):
  estados = (('pendiente', 'Pendiente'), ('rechazada', 'Rechazada'), ('aprobada', 'Aprobada'))
  
  inmueble = models.ForeignKey(Inmueble, on_delete=models.CASCADE, related_name='solicitudes')
  arrendador = models.ForeignKey(User, related_name='solicitudes', on_delete=models.CASCADE)
  fecha = models.DateTimeField(auto_now_add=True)
  estado = models.CharField(max_length=50, choices=estados)

inmuebles/forms.py
from django.forms import ModelForm
from main.models import Inmueble
from django import forms

class InmuebleForm(ModelForm):
    class Meta:
        model = Inmueble
        exclude = []  # Puedes listar los campos a excluir si es necesario
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control'}),
            'm2_construidos': forms.NumberInput(attrs={'class': 'form-control'}),
            'm2_totales': forms.NumberInput(attrs={'class': 'form-control'}),
            'num_estacionamientos': forms.NumberInput(attrs={'class': 'form-control'}),
            'num_habitaciones': forms.NumberInput(attrs={'class': 'form-control'}),
            'num_baños': forms.NumberInput(attrs={'class': 'form-control'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_inmueble': forms.TextInput(attrs={'class': 'form-control'}),
            'precios': forms.NumberInput(attrs={'class': 'form-control'}),
            'precios_ufs': forms.NumberInput(attrs={'class': 'form-control', 'required': False}),
            'comuna': forms.Select(attrs={'class': 'form-control'}),
            'propietario': forms.Select(attrs={'class': 'form-control'}),
            'imagen': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

inmuebles/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from main.models import Inmueble, Region, Comuna
from main.services import crear_inmueble as crear_inmueble_service, eliminar_inmueble as eliminar_inmueble_service
from inmuebles.forms import InmuebleForm

# vamos a crear un test que sólo pasan los 'arrendadores'
def solo_arrendadores(user):
    if user.user_profile.rol == 'arrendador' or user.is_staff == True:
        return True
    else:
        return False

@user_passes_test(solo_arrendadores)
def editar_inmueble(req, id):
    # Obtengo el inmueble a editar
    inmueble = get_object_or_404(Inmueble, id=id)

    if req.method == 'GET':
        # Obtengo las regiones y comunas
        regiones = Region.objects.all()
        comunas = Comuna.objects.all()
        # Obtengo el código de la región
        cod_region_actual = inmueble.comuna.cod[0:2]
        # Creo el 'context' con toda la info que requiere el template
        context = {
            'inmueble': inmueble,
            'regiones': regiones,
            'comunas': comunas,
            'cod_region': cod_region_actual
        }
        return render(req, 'editar_inmueble.html', context)
    
    elif req.method == 'POST':
        # Actualizo el inmueble con los datos del formulario
        inmueble.nombre = req.POST.get('nombre')
        inmueble.descripcion = req.POST.get('descripcion')
        inmueble.m2_construidos = req.POST.get('m2_construidos')
        inmueble.m2_totales = req.POST.get('m2_totales')
        inmueble.num_estacionamientos = req.POST.get('num_estacionamientos')
        inmueble.num_habitaciones = req.POST.get('num_habitaciones')
        inmueble.num_baños = req.POST.get('num_baños')
        inmueble.direccion = req.POST.get('direccion')
        inmueble.tipo_inmueble = req.POST.get('tipo_inmueble')
        inmueble.precio = req.POST.get('precio')
        comuna_cod = req.POST.get('comuna_cod')
        if comuna_cod:
            inmueble.comuna = get_object_or_404(Comuna, cod=comuna_cod)

        # Manejo de la imagen
        if 'imagen' in req.FILES:
            inmueble.imagen = req.FILES['imagen']

        inmueble.save()

        # Agregar mensaje de éxito
        messages.success(req, 'Inmueble editado con éxito.')

        return redirect('/accounts/profile/')
    
    else:
        return HttpResponse('Método no permitido', status=405)

@user_passes_test(solo_arrendadores)
def nuevo_inmueble(req):
    if req.method == 'GET':
        # Obtener las regiones y comunas
        regiones = Region.objects.all()
        comunas = Comuna.objects.all()
        # Pasar los datos requeridos por el formulario
        context = {
            'tipos_inmueble': Inmueble.tipos,
            'regiones': regiones,
            'comunas': comunas
        }
        return render(req, 'nuevo_inmueble.html', context)
    
    elif req.method == 'POST':
        # Crear una instancia de Inmueble con los datos del formulario
        inmueble = Inmueble(
            nombre=req.POST.get('nombre'),
            descripcion=req.POST.get('descripcion'),
            m2_construidos=req.POST.get('m2_construidos'),
            m2_totales=req.POST.get('m2_totales'),
            num_estacionamientos=req.POST.get('num_estacionamientos'),
            num_habitaciones=req.POST.get('num_habitaciones'),
            num_baños=req.POST.get('num_baños'),
            direccion=req.POST.get('direccion'),
            tipo_inmueble=req.POST.get('tipo_inmueble'),
            precio=req.POST.get('precio')
        )
        comuna_id = req.POST.get('comuna')
        if comuna_id:
            inmueble.comuna = get_object_or_404(Comuna, id=comuna_id)

        # Manejo de la imagen
        if 'imagen' in req.FILES:
            inmueble.imagen = req.FILES['imagen']

        # Guardar el nuevo inmueble
        inmueble.save()
        return redirect('/accounts/profile/')
    
    else:
        return HttpResponse('Método no permitido', status=405)


@user_passes_test(solo_arrendadores)
def eliminar_inmueble(req, id):
    eliminar_inmueble_service(id)
    messages.error(req, 'Inmueble ha sido eliminado')
    return redirect('/accounts/profile/')

@user_passes_test(solo_arrendadores)
def crear_inmueble(req):
    # obtener el rut del usuario
    propietario_rut = req.user.username
    # validar metraje (construídos vs totales)
    crear_inmueble_service(
    req.POST['nombre'],
    req.POST['descripcion'],
    int(req.POST['m2_construidos']),
    int(req.POST['m2_totales']),
    int(req.POST['num_estacionamientos']),
    int(req.POST['num_habitaciones']),
    int(req.POST['num_baños']),
    req.POST['direccion'],
    req.POST['tipo_inmueble'],
    int(req.POST['precio']),
    req.POST['comuna_cod'],
    propietario_rut
    )
    messages.success(req, 'Propiedad Creada')
    return redirect('/accounts/profile/')

@user_passes_test(solo_arrendadores)
def nuevo_inmueble(req):
    # nos traemos la información de las comunas y las regiones
    regiones = Region.objects.all()
    comunas = Comuna.objects.all()
    # pasar los datos requeridos por el formulario
    context = {
    'tipos_inmueble': Inmueble.tipos,
    'regiones': regiones,
    'comunas': comunas
    }
    return render(req, 'nuevo_inmueble.html', context)

inmuebles/templates/editar_inmueble.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="p-4 border rounded bg-light mt-4">
    <h3 class="text-center">
      Editando la Propiedad<br>
      <h4 class="text-center" style="color: royalblue;">{{ inmueble.nombre }}</h4>
    </h3>
  </div>
  <div class="card shadow-lg mb-4">
    <div class="card-body">
  <form action="{% url 'editar_inmueble' id=inmueble.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
      <div class="col-4 p-3">

        <div class="mb-3">
          <label for="nombre" class="form-label">Nombre:</label>
          <input type="text" class="form-control" id="nombre" required placeholder="nombre de la propiedad" name="nombre" value="{{ inmueble.nombre }}">
        </div>
        
        <div class="mb-3">
          <label for="descripcion" class="form-label">Descripción:</label>
          <textarea name="descripcion" class="form-control" id="descripcion" rows="3" required maxlength="1500" placeholder="breve descripción...">{{inmueble.descripcion}}</textarea>
        </div>

        <div class="mb-3">
          <label for="nombre" class="form-label">Metros Construídos:</label>
          <input min="1" name="m2_construidos" type="number" class="form-control" id="m2_construidos" required placeholder="23 m^2" value="{{inmueble.m2_construidos}}">
        </div>
        
        <div class="mb-3">
          <label for="nombre" class="form-label">Metros Totales:</label>
          <input min="1" name="m2_totales" type="number" class="form-control" id="m2_totales" required placeholder="50 m^2" value="{{inmueble.m2_totales}}">
        </div>
      </div>
      <div class="col-4 p-3">
        <!-- num_estacionamientos, num_habitaciones, num_baños, direccion -->
        <div class="mb-3">
          <label for="nombre" class="form-label">Num. Estacionamientos:</label>
          <input min="0" name="num_estacionamientos" type="number" class="form-control" id="num_estacionamientos" required placeholder="num"  value="{{inmueble.num_estacionamientos}}">
        </div>
        
        <div class="mb-3">
          <label for="nombre" class="form-label">Num. Habitaciones:</label> 
          <input min="0" name="num_habitaciones" type="number" class="form-control" id="num_habitaciones" required placeholder="num" value="{{inmueble.num_habitaciones}}" >
        </div>
        
        <div class="mb-3">
          <label for="nombre" class="form-label">Num. Baños:</label>
          <input min="0" name="num_baños" type="number" class="form-control" id="num_baños" required placeholder="num" value="{{ inmueble.num_baños }}">
        </div>

        <div class="mb-3">
          <label for="nombre" class="form-label">Dirección:</label>
          <input type="text" class="form-control" id="direccion" required placeholder="tu dirección" name="direccion" value="{{inmueble.direccion}}">
        </div>

      </div>
      <div class="col-4 p-3">
        <div class="mb-3">
          <select class="form-select" required name="tipo_inmueble">
            <option value>Selecciona un tipo</option>
            {% for tt in inmueble.tipos %}
              <option
                value="{{ tt.0 }}"
                {% if tt.0 == inmueble.tipo_inmueble %}selected{% endif %}>
                {{ tt.1 }}
              </option>
            {% endfor %}
          </select>
        </div>

        <div class="mb-3">
          <label for="nombre" class="form-label">Precio (CLP):</label>
          <input min="1000" name="precio" type="number" class="form-control" id="precio" required placeholder="$250.000" value="{{inmueble.precio}}">
        </div>

        <div class="mb-3">
          <select class="form-select" name="region_cod" id="region_cod">
            <option value>Selecciona una Región</option>
            {% for region in regiones %}
              <option
                value="{{ region.cod }}"
                {% if region.cod == cod_region %}selected{% endif %}
              >
                {{ region.nombre }}
              </option>
            {% endfor %}
          </select>
        </div>
        
        <div class="mb-3">
          <select class="form-select" required name="comuna_cod" id="comuna_cod">
            <option value>Selecciona una Comuna</option>
            {% for comuna in comunas %}
              <option
                value="{{ comuna.cod }}"
                {% if comuna.cod == inmueble.comuna_id %}selected{% endif %}
                >{{ comuna.nombre }}
              </option>
            {% endfor %}
          </select>
        </div>
        <div class="mb-3">
          <label for="imagen" class="form-label">Imagen:</label>
          <input type="file" class="form-control" id="imagen" name="imagen">
          {% if inmueble.imagen %}
            <img src="{{ inmueble.imagen.url }}" alt="Imagen actual" class="img-fluid mt-2" style="max-width: 100%;">
          {% endif %}
        </div>
      </div>
    </div>
    <div class="text-center">
      <button type="submit" class="btn btn-success">Editar</button>
    </div>
  </form>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script>
  function filtrar_comunas () {
    // recuperamos el valor seleccionado de la Region
    const cod_seleccionado = $(this).val()
    console.log(cod_seleccionado)
    // ahora iteramos sobre todas las comunas, y mostramos sólo aquellas cuyo código tenga como prefijo el código de la región seleccionada
    $('#comuna_cod option').each(function() {
      const comuna = $(this)
      const cod_comuna = comuna.val()
      if (cod_seleccionado == cod_comuna.substring(0, 2)) {
        // la comuna es parte de la region
        comuna.show()
      } else {
        comuna.hide()
      }
    })
  }

  $('#region_cod').on('change', filtrar_comunas)
</script>
{% endblock %}

inmuebles/templates/inmueble_detail.html
<div class="modal fade" id="inmuebleModal" tabindex="-1" aria-labelledby="inmuebleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="inmuebleModalLabel">{{ inmueble.nombre }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row mb-3">
                    <div class="col-12">

                        <p class="lead">{{ inmueble.descripcion }}</p>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <p><strong>Metros Construidos:</strong> {{ inmueble.m2_construidos }} m²</p>
                        <p><strong>Metros Totales:</strong> {{ inmueble.m2_totales }} m²</p>
                        <p><strong>Estacionamientos:</strong> {{ inmueble.num_estacionamientos }}</p>
                        <p><strong>Habitaciones:</strong> {{ inmueble.num_habitaciones }}</p>
                        <p><strong>Baños:</strong> {{ inmueble.num_baños }}</p>
                    </div>
                    <div class="col-md-6">
                        <p><strong>Dirección:</strong> {{ inmueble.direccion }}</p>
                        <p><strong>Tipo de Inmueble:</strong> {{ inmueble.get_tipo_inmueble_display }}</p>
                        <p><strong>Precio:</strong> {{ inmueble.precio }}</p>
                        <p><strong>Comuna:</strong> {{ inmueble.comuna.nombre }}</p>
                        <p><strong>Propietario:</strong> {{ inmueble.propietario.first_name }} {{inmueble.propietario.last_name }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6 text-center mb-3">
                        {% if inmueble.imagen %}
                        <img src="{{ inmueble.imagen.url }}" alt="{{ inmueble.nombre }}" class="img-fluid rounded">
                        {% else %}
                        <p class="text-muted">No hay imagen disponible</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>

    </div>
</div>

inmuebles/templates/inmueble_detail_modal.html
<div class="modal-header">
    <h5 class="modal-title" id="inmuebleModalLabel">{{ inmueble.nombre }}</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <div class="row mb-3">
        <div class="col-12">
            <p class="lead">{{ inmueble.descripcion }}</p>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md-6">
            <p><strong>Metros Construidos:</strong> {{ inmueble.m2_construidos }} m²</p>
            <p><strong>Metros Totales:</strong> {{ inmueble.m2_totales }} m²</p>
            <p><strong>Estacionamientos:</strong> {{ inmueble.num_estacionamientos }}</p>
            <p><strong>Habitaciones:</strong> {{ inmueble.num_habitaciones }}</p>
            <p><strong>Baños:</strong> {{ inmueble.num_baños }}</p>
        </div>
        <div class="col-md-6">
            <p><strong>Dirección:</strong> {{ inmueble.direccion }}</p>
            <p><strong>Tipo de Inmueble:</strong> {{ inmueble.get_tipo_inmueble_display }}</p>
            <p><strong>Precio:</strong> {{ inmueble.precio }}</p>
            <p><strong>Comuna:</strong> {{ inmueble.comuna.nombre }}</p>
            <p><strong>Propietario:</strong> {{ inmueble.propietario.first_name }} {{ inmueble.propietario.last_name }}
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-6 text-center mb-3">
            {% if inmueble.imagen %}
            <img src="{{ inmueble.imagen.url }}" alt="{{ inmueble.nombre }}" class="img-fluid rounded">
            {% else %}
            <p class="text-muted">No hay imagen disponible</p>
            {% endif %}
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
</div>

inmuebles/templates/nuevo_inmueble.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
  <div class="p-4 border rounded bg-light">
    <h3 class="text-center mb-0">Agrega una Nueva Propiedad</h3>
  </div>
  <div class="card shadow-lg">
    <div class="card-body">
  <form action="/inmuebles/crear/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
      <div class="col-4 p-3">

        <div class="mb-3">
          <label for="nombre" class="form-label">Nombre:</label>
          <input type="text" class="form-control" id="nombre" required placeholder="nombre de la propiedad" name="nombre">
        </div>
        
        <div class="mb-3">
          <label for="descripcion" class="form-label">Descripción:</label>
          <textarea name="descripcion" class="form-control" id="descripcion" rows="3" required maxlength="1500" placeholder="breve descripción..."></textarea>
        </div>

        <div class="mb-3">
          <label for="nombre" class="form-label">Metros Construídos:</label>
          <input min="1" name="m2_construidos" type="number" class="form-control" id="m2_construidos" required placeholder="23 m^2">
        </div>
        
        <div class="mb-3">
          <label for="nombre" class="form-label">Metros Totales:</label>
          <input min="1" name="m2_totales" type="number" class="form-control" id="m2_totales" required placeholder="50 m^2">
        </div>
      </div>
      <div class="col-4 p-3">
        <!-- num_estacionamientos, num_habitaciones, num_baños, direccion -->
        <div class="mb-3">
          <label for="nombre" class="form-label">Num. Estacionamientos:</label>
          <input min="0" value="0" name="num_estacionamientos" type="number" class="form-control" id="num_estacionamientos" required placeholder="num">
        </div>
        
        <div class="mb-3">
          <label for="nombre" class="form-label">Num. Habitaciones:</label>
          <input min="0" value="0" name="num_habitaciones" type="number" class="form-control" id="num_habitaciones" required placeholder="num">
        </div>
        
        <div class="mb-3">
          <label for="nombre" class="form-label">Num. Baños:</label>
          <input min="0" value="0" name="num_baños" type="number" class="form-control" id="num_baños" required placeholder="num">
        </div>

        <div class="mb-3">
          <label for="nombre" class="form-label">Dirección:</label>
          <input type="text" class="form-control" id="direccion" required placeholder="tu dirección" name="direccion">
        </div>

        <div class="mb-3">
          <label for="imagen" class="form-label">Imagen:</label>
          <input type="file" class="form-control" id="imagen" name="imagen">
      </div>

      </div>
      <div class="col-4 p-3">
        <div class="mb-3">
          <select class="form-select" required name="tipo_inmueble">
            <option value>Selecciona un tipo</option>
            {% for tipo in tipos_inmueble %}
              <option value="{{ tipo.0 }}">{{ tipo.1 }}</option>
            {% endfor %}
          </select>
        </div>

        <div class="mb-3">
          <label for="nombre" class="form-label">Precio (CLP):</label>
          <input min="1000" name="precio" type="number" class="form-control" id="precio" required placeholder="$250.000">
        </div>

        <div class="mb-3">
          <select class="form-select" name="region_cod" id="region_cod">
            <option value>Selecciona una Región</option>
            {% for region in regiones %}
              <option value="{{ region.cod }}">{{ region.nombre }}</option>
            {% endfor %}
          </select>
        </div>
        
        <div class="mb-3">
          <select class="form-select" required name="comuna_cod" id="comuna_cod">
            <option value>Selecciona una Comuna</option>
            {% for comuna in comunas %}
              <option value="{{ comuna.cod }}">{{ comuna.nombre }}</option>
            {% endfor %}
          </select>
        </div>

      </div>
    </div>
    <div class="text-center">
      <button type="submit" class="btn btn-success">Crear Propiedad</button>
    </div>
  </form>
</div>
</div>
</div>
{% endblock %}

{% block js %}
<script>
  function filtrar_comunas () {
    // recuperamos el valor seleccionado de la Region
    const cod_seleccionado = $(this).val()
    console.log(cod_seleccionado)
    // ahora iteramos sobre todas las comunas, y mostramos sólo aquellas cuyo código tenga como prefijo el código de la región seleccionada
    $('#comuna_cod option').each(function() {
      const comuna = $(this)
      const cod_comuna = comuna.val()
      if (cod_seleccionado == cod_comuna.substring(0, 2)) {
        // la comuna es parte de la region
        comuna.show()
      } else {
        comuna.hide()
      }
    })
  }

  $('#region_cod').on('change', filtrar_comunas)
</script>
{% endblock %}